org: renzordiaz
app: lharb-serverless-lambda
service: lharb-serverless-lambda
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:095273127390:table/TodoTable

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /create/
          method: post
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          path: /
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          path: /{id}
          method: get
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          path: /{id}
          method: patch
  deleteTodo:
    handler: src/deleteTodo.handler
    events:
      - http:
          path: /{id}
          method: delete

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
